#!/usr/bin/env bash
# A bash script that displays `Best School` but 9th iteration displays `Best School` and `Hi`

i=0
while [[ "$i" -lt 10 ]]
do
	if [ "$i" = 9 ]
	then
	echo "Hi"
	fi
	echo "Best School"
	((i++))
done
